---
- name: Install nc kube definition.
  ansible.builtin.template:
    src: templates/kube/nextcloud.yml.j2
    dest: "{{ nc_volumes_dir }}/nextcloud.yml"
    mode: "0644"

- name: Ensure Podman network for nc exists.
  containers.podman.podman_network:
    name: "{{ nc_network }}"
    state: present

- name: Ensure nc is deployed.
  containers.podman.podman_play:
    kube_file: "{{ nc_volumes_dir }}/nextcloud.yml"
    state: created
    recreate: true
    network: "{{ nc_network }}"

- name: Generate systemd units for {{ nc_pod_name }}.
  containers.podman.podman_generate_systemd:
    name: "{{ nc_pod_name }}"
    dest: "/home/{{ nc_user }}/.config/systemd/user/"
    restart_policy: on-failure
    force: true

- name: Ensure systemd units are started and enabled for {{ nc_pod_name }}.
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "pod-{{ nc_pod_name }}"
    state: started
    enabled: true
