---
- name: Ensure systemd service is copied for nextcloud cron job.
  ansible.builtin.template:
    src: templates/systemd/cron.service.j2
    dest: /home/{{ nc_user }}/.config/systemd/user/cron-{{ nc_pod_name }}-{{ nc_container_name }}.service
    mode: "644"
    owner: "{{ nc_user }}"
    group: "{{ nc_user }}"

- name: Ensure systemd timer is copied for nextcloud cron job.
  ansible.builtin.template:
    src: templates/systemd/cron.timer.j2
    dest: /home/{{ nc_user }}/.config/systemd/user/cron-{{ nc_pod_name }}-{{ nc_container_name }}.timer
    mode: "644"
    owner: "{{ nc_user }}"
    group: "{{ nc_user }}"

- name: Ensure systemd timer and service are stared and enabled for nextcloud cron job.
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "cron-{{ nc_pod_name }}-{{ nc_container_name }}.timer"
    enabled: true
    state: started
