---
- name: Import storage tasks.
  ansible.builtin.import_tasks: storage.yml

- name: Run tasks under user {{ nc_user }}.
  become: true
  become_user: "{{ nc_user }}"
  block:
    - name: Import app tasks.
      ansible.builtin.import_tasks: app.yml

    - name: Import cron tasks.
      ansible.builtin.import_tasks: cron.yml
