---
nc_user: "{{ ansible_user }}"
nc_network: nc

nc_pod_name: nc
nc_container_name: nextcloud

nc_http_port: 8080

# images
nc_image_name: "docker.io/library/nextcloud"
nc_image_tag: "28.0.2"

# directories
nc_volumes_dir: "/srv/nc"

# env vars: NEXTCLOUD
nc_admin_user: admin
nc_admin_password: nextcloud
nc_overwriteprotocol: "http"
nc_overwritecliurl: ""
nc_trusted_domains: "{{ ansible_host }}"
nc_trusted_proxies: []

# database vars
nc_postgres_host: "{{ ansible_host }}"
nc_postgres_user: nextcloud
nc_postgres_db: nextcloud
nc_postgres_password: nextcloud

# redis
nc_redis_host: "{{ ansible_host }}"
nc_redis_port: 6379
