---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: nc
    box: rockylinux/9
    memory: 2048
    cpu: 2
provisioner:
  name: ansible
verifier:
  name: ansible
