---
- name: Prepare
  hosts: all
  become: true

  vars_files:
    - vars/db.yml
    - vars/nc.yml

  tasks:
    - name: Include epel role.
      ansible.builtin.include_role:
        name: palekiwi.epel

    - name: Ensure podman is installed.
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Enable linger for user {{ nc_user }}
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ nc_user }}"
      changed_when: true

    - name: Setup database.
      become: true
      become_user: "{{ nc_user }}"
      block:
        - name: Install db kube definition.
          ansible.builtin.template:
            src: templates/postgres.yml.j2
            dest: "/tmp/postgres.yml"
            mode: "0644"

        - name: Ensure postgres is deployed.
          containers.podman.podman_play:
            kube_file: /tmp/postgres.yml
            state: started
            recreate: true
            network: host
